### ISSUE TITLE
Conversion of 12C OCP Upgrade Wiki pages to Jekyll format.

### ISSUE THREAD

**Issue by dfhawthorne** [dfhawthorne/dfhawthorne.github.io#51]

**Comment by dfhawthorne** [comment]
Final conversion of Section 1 has the following errors:

```bash
for f in $(find_unconverted_web_pages.sh| grep section-1)
do b=$(basename $f)
   convert_web_page.py -rgvl /tmp/${b}.log $f
done
```

```text
Traceback (most recent call last):
  File "/home/douglas/bin/convert_web_page.py", line 66, in <module>
    with open(args.input_html_file_name[0], 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/douglas/git-repositories/dfhawthorne.github.io/docs/home/12c-ocp-upgrade/section-1-new-features-of-oracle-database-12c/emergency-monitoring-real-time-addm-compare-period-addm-and-active-session-history-ash-analytics/generate-addm-compare-period.html'
Traceback (most recent call last):
  File "/home/douglas/bin/convert_web_page.py", line 66, in <module>
    with open(args.input_html_file_name[0], 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/douglas/git-repositories/dfhawthorne.github.io/docs/home/12c-ocp-upgrade/section-1-new-features-of-oracle-database-12c/emergency-monitoring-real-time-addm-compare-period-addm-and-active-session-history-ash-analytics/diagnose-performance-issues-using-ash-enhancements.html'
Traceback (most recent call last):
  File "/home/douglas/bin/convert_web_page.py", line 66, in <module>
    with open(args.input_html_file_name[0], 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/douglas/git-repositories/dfhawthorne.github.io/docs/home/12c-ocp-upgrade/section-1-new-features-of-oracle-database-12c/emergency-monitoring-real-time-addm-compare-period-addm-and-active-session-history-ash-analytics/perform-emergency-monitoring-and-real-time-addm.html'
/home/douglas/git-repositories/dfhawthorne.github.io/docs/home/11g-oce-rac/section-1---grid-infrastructure-clusterware-and-asm/making-applications-highly-available-with-oracle-clusterware/describe-the-high-availability-components-of-oracle-clusterware.html is a New Google Sites page
```

**Comment by dfhawthorne** [comment]
Visible verification of converted section 1 pages has been done. The changes to the above pages have been rolled back. The remaining section 1 pages to be converted were found by the following commands:

```bash
find_unconverted_web_pages.sh | \
    grep '12c-ocp-upgrade/section-1' | \
    cut -d/ -f10- 
```

The results were:

```text
resource-manager-and-other-performance-enhancements/explain-multi-process-multi-threaded-oracle-architecture.html
resource-manager-and-other-performance-enhancements/use-resource-manager-for-a-cdb-and-pdb.html
resource-manager-and-other-performance-enhancements/use-flash-cache.html
emergency-monitoring-real-time-addm-compare-period-addm-and-active-session-history-ash-analytics.html
emergency-monitoring-real-time-addm-compare-period-addm-and-active-session-history-ash-analytics/generate-addm-compare-period.html
emergency-monitoring-real-time-addm-compare-period-addm-and-active-session-history-ash-analytics/diagnose-performance-issues-using-ash-enhancements.html
emergency-monitoring-real-time-addm-compare-period-addm-and-active-session-history-ash-analytics/perform-emergency-monitoring-and-real-time-addm.html
```

**Comment by dfhawthorne** [comment]
Did conversion of section 2 pages using the following commands:

```bash
for f in $(find_unconverted_web_pages.sh| grep $(pwd))
do echo $f
   b=$(basename $f)
   convert_web_page.py -rgvl /tmp/${b}.log $f
done
```

**Comment by dfhawthorne** [comment]
Visually validated section 2 pages.
